### ISSUE TITLE
Error: Couldn't find preset "es2016"

### ISSUE THREAD

**Issue by samcrane8** [tjohnn/vuejs-datetimepicker#20]
I added your component and imported it into one of my components, but I go this error:

```
> demo-drone-app@1.0.0 dev /Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% asset optimization

 ERROR  Failed to compile with 1 errors                                                                                                                                                    10:24:11

 error  in ./node_modules/vuejs-datetimepicker/src/datetime_picker.vue

Module build failed: Error: Couldn't find preset "es2016" relative to directory "/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/vuejs-datetimepicker"
    at /Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:
20)
    at OptionManager.mergePresets (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/samcrane/Documents/Repositories/SAR-Spring-2018/Front-End/demo-drone-app/node_modules/babel-loader/lib/index.js:175:20)

 @ ./node_modules/vuejs-datetimepicker/src/datetime_picker.vue 8:0-102 9:0-115
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/FlightsPage/FlightFilters/FilterItem.vue
 @ ./src/views/FlightsPage/FlightFilters/FilterItem.vue
 @ ./src/views lazy ^\.\/.*\.vue$
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by tjohnn** [comment]
Have you tried the solution from #16 ?

**Comment by Chemahin** [comment]
+1   "Couldn't find preset "es2016" relative to directory"

**Comment by vmartins** [comment]
Try:
```
npm i babel-preset-es2016 --save-dev
```
